swagger: "2.0"
info:
  version: "1.0.0"
  title: "Occurences de taxon - SINP"
  description: "Export de JDD d'occurences format SINP"
  termsOfService: http://example.com/terms/
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: "Classification"
    description: "Ensemble des termes de classification des taxons"
  - name: "Reconnaissance"
    description: "Critères de reconnaissances des taxons"
  - name: "Geo-localisation"
    description: "Opérations de localisation autour des taxons"
  - name: "Temporelle"
    description: "Opérations temporelle autour des taxons"
  - name: "Observateur"
    description: "Operations autour de l'observateur"
# host: "localhost:8000"
servers:
  - url: http://localhost:4200/#/exports/  # FIXME: API_ENDPOINT + api_url
    description: Development server
  - url: http://http://demo.geonature.fr/geonature/#/
    description: Production server
basePath: "/exports/"
schemes:
  - "http"
produces:
  - "application/json"
  - "application/csv"
  - "application/zip"
consumes:
  - "application/json"
paths:
  /cdRef:
    get:
      tags:
      - "Classification"
      responses:
        405:
          description: "Invalid input"
  /cdNom:
    get:
      tags:
      - "Classification"
      responses:
        405:
          description: "Invalid input"
  /regne:
    get:
      tags:
      - "Classification"
      responses:
        405:
          description: "Invalid input"
  /famille:
    get:
      tags:
      - "Classification"
      responses:
        405:
          description: "Invalid input"
  /groupe:
    get:
      tags:
      - "Classification"
      responses:
        405:
          description: "Invalid input"
  /obsTechnique:
    get:
      tags:
      - "Reconnaissance"
      responses:
        405:
          description: "Invalid input"
  /bioStatus:
    get:
      tags:
      - "Reconnaissance"
      responses:
        405:
          description: "Invalid input"
  /bioCondition:
    get:
      tags:
      - "Reconnaissance"
      responses:
        405:
          description: "Invalid input"
  /sex:
    get:
      tags:
      - "Reconnaissance"
      responses:
        405:
          description: "Invalid input"
  /blurring:
    get:
      tags:
      - "Reconnaissance"
      responses:
        405:
          description: "Invalid input"
  /existProof:
    get:
      tags:
      - "Reconnaissance"
      responses:
        405:
          description: "Invalid input"
  /altitudeMin:
    get:
      tags:
      - "Geo-localisation"
      responses:
        405:
          description: "Invalid input"
  /altitudeMax:
    get:
      tags:
      - "Geo-localisation"
      responses:
        405:
          description: "Invalid input"
  /municipality:
    get:
      tags:
      - "Geo-localisation"
      responses:
        405:
          description: "Invalid input"
  /dateMin:
    get:
      tags:
      - "Temporelle"
      responses:
        405:
          description: "Invalid input"
  /dateMax:
    get:
      tags:
      - "Temporelle"
      responses:
        405:
          description: "Invalid input"
  /hourMin:
    get:
      tags:
      - "Temporelle"
      responses:
        405:
          description: "Invalid input"
  /hourMax:
    get:
      tags:
      - "Temporelle"
      responses:
        405:
          description: "Invalid input"
  /observers:
    get:
      tags:
      - "Observateur"
      responses:
        405:
          description: "Invalid input"
  /determiner:
    get:
      tags:
      - "Observateur"
      responses:
        405:
          description: "Invalid input"
