swagger: "2.0"
info:
  version: "0.1.0"
  title: "Exports de JDD concernant la biodiversité"
  description: "Export de vos jeux de données GéoNature aux formats geojson, csv et shapefile"
  contact:
    name: API Support
    url: https://github.com/PnX-SI/GeoNature/issues
    email: geonature@ecrins-parcnational.fr
  license:
    name: GNU General Public License v3.0
    url: https://raw.githubusercontent.com/PnX-SI/GeoNature/master/LICENSE
externalDocs:
  description: "Find out more about GéoNature"
  url: "http://geonature.fr"
host: localhost:8000
basePath:
schemes:
  - https
  - http
produces:
  - application/json
consumes:
  - application/json
definitions:
  Export:
    type: object
    properties:
      id:
        type: integer
        minimum: 1
      label:
        type: string
      schema_name:
        type: string
      view_name:
        type: string
    required:
      - id
  Login:
    type: object
    properties:
      login:
        type: string
        default: admin
      password:
        type: string
        format: password
        default: admin
      id_application:
        type: integer
        default: 3
      with_cruved:
        type: boolean
        default: true
  Cruved:
    type: object
    properties:
      user:
        type: object
        properties:
          id_application:
            type: integer  # 3
          id_tag_action:
            type: integer  # 11
            maxLength: 2
          nom_role:
            type: string  # Administrateur
          identifiant:
            type: string  # admin
          rights:
            type: object
            properties:
              '3':
                type: object
                properties:
                  'R':
                    type: string  # '3'
                    maxLength: 1
                  'D':
                    type: string  # '3'
                    maxLength: 1
                  'E':
                    type: string  # '3'
                    maxLength: 1
                  'C':
                    type: string  # '3'
                    maxLength: 1
                  'V':
                    type: string  # '3'
                    maxLength: 1
                  'U':
                    type: string  # '3'
                    maxLength: 1
          id_organisme:
            type: integer  # -1
          tag_action_code:
            type: string  # 'C'
          prenom_role:
            type: string  # 'test'
          id_role:
            type: integer  # 1
          id_tag_object:
            type: integer  # 23
          tag_object_code:
            type: string  # '3'
      expires:
        type: string  # '2018-10-16 00:36:15.491613'
        format: datetime
  Error:
    type: object
    properties:
     message:
      type: string
     error:
      type: string
securityDefinitions:
  # tokenAuth:
  #   type: apiKey
  #   in: cookie
  #   name: token
  bearerAuth:
    type: apiKey
    in: header
    name: Authorization
paths:
  /auth/login:
    post:
      tags:
        - Authentification
      security:
        - bearerAuth: []
      summary:  Allow users to log in and to receive a token
      parameters:
        -
         in: body
         name: body
         description: username/password combination
         required: true
         schema:
           $ref: '#/definitions/Login'
      responses:
        '200':
           description: Login Success
           schema:
             $ref: '#/definitions/Cruved'
        '500':
           description:
             If supplied with invalid credentials
           schema:
             $ref: '#/definitions/Error'
  /export/:
    get:
      security:
        # - tokenAuth: []
        - bearerAuth: []
      summary: Returns all exports the user has access to
      tags:
        - Exports
      responses:
        '200':
          description: A list of export
          schema:
            type: array
            items:
              $ref: '#/definitions/Export'
        '404':
          description: No configured exports
        '400':
          description: Unexpected usage
        '403':
          description: Unauthenticated
  /export/{id}/{format}:
    get:
      security:
        # - tokenAuth: []
        - bearerAuth: []
      summary: Returns the format-specified data from the export the user has access to.
      tags:
        - Exports
      produces:
        - application/json
        - text/csv
        - application/zip
      responses:
        '200':
          description: Export data into a file
          schema:
            type: file
          headers:
            Content-Disposition:
              type: string
              description: attachment; filename=export_{Export.label}_{datetime.now().strftime('%Y_%m_%d_%Hh%Mm%S')}.{extension}
        '404':
          description: No configured export | Empty dataset | Unsuitable format
        '400':
          description: Unexpected usage
        '403':
          description: Unauthenticated | Insufficient rights