swagger: "2.0"
info:
  version: "0.1.0"
  title: "Exports de JDD concernant la biodiversité"
  description: "Export de vos jeux de données GéoNature aux formats geojson, csv et shapefile"
  contact:
    name: API Support
    url: https://github.com/PnX-SI/GeoNature/issues
    email: geonature@ecrins-parcnational.fr
  license:
    name: GNU General Public License v3.0
    url: https://raw.githubusercontent.com/PnX-SI/GeoNature/master/LICENSE
externalDocs:
  description: "Find out more about GéoNature"
  url: "http://geonature.fr"
host: {{HOST}}
basePath: {{BASE_PATH}}
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
definitions:
  Export:
    type: object
    properties:
      id:
        type: integer
        minimum: 1
      label:
        type: string
      schema_name:
        type: string
      view_name:
        type: string
    required:
      - id
  Login:
    type: object
    properties:
      login:
        type: string
        default: admin
      password:
        type: string
        format: password
        default: admin
      id_application:
        type: integer
        default: 3
      with_cruved:
        type: boolean
        default: true
  Cruved:
    type: object
    properties:
      user:
        type: object
        properties:
          id_application:
            type: integer  # 3
          id_tag_action:
            type: integer  # 11
            maxLength: 2
          nom_role:
            type: string  # Administrateur
          identifiant:
            type: string  # admin
          rights:
            type: object
            properties:
              '3':
                type: object
                properties:
                  'R':
                    type: string  # '3'
                    maxLength: 1
                  'D':
                    type: string  # '3'
                    maxLength: 1
                  'E':
                    type: string  # '3'
                    maxLength: 1
                  'C':
                    type: string  # '3'
                    maxLength: 1
                  'V':
                    type: string  # '3'
                    maxLength: 1
                  'U':
                    type: string  # '3'
                    maxLength: 1
          id_organisme:
            type: integer  # -1
          tag_action_code:
            type: string  # 'C'
          prenom_role:
            type: string  # 'test'
          id_role:
            type: integer  # 1
          id_tag_object:
            type: integer  # 23
          tag_object_code:
            type: string  # '3'
      expires:
        type: string  # '2018-10-16 00:36:15.491613'
        format: datetime
  Error:
    type: object
    properties:
     message:
      type: string
     error:
      type: string
securityDefinitions:
  # tokenAuth:
  #   type: apiKey
  #   in: cookie
  #   name: token
  bearerAuth:
    type: apiKey
    in: header
    name: Authorization
paths:
  /auth/login:
    post:
      tags:
        - Authentification
      security:
        - bearerAuth: []
      summary:  Allow users to log in and to receive a token
      parameters:
        -
         in: body
         name: body
         description: username/password combination
         required: true
         schema:
           $ref: '#/definitions/Login'
      responses:
        '200':
           description: Login Success
           schema:
             $ref: '#/definitions/Cruved'
        '500':
           description:
             If supplied with invalid credentials
           schema:
             $ref: '#/definitions/Error'
  /{{API_URL}}/:
    get:
      security:
        # - tokenAuth: []
        - bearerAuth: []
      summary: Returns all exports the user has access to
      tags:
        - Exports
      responses:
        '200':
          description: A list of export
          schema:
            type: array
            items:
              $ref: '#/definitions/Export'
        '404':
          description: No configured exports
        '400':
          description: Unexpected usage
        '403':
          description: Unauthenticated
  /{{API_URL}}/{id}/{format}:
    get:
      security:
        # - tokenAuth: []
        - bearerAuth: []
      summary: Returns the format-specified data from the export the user has access to.
      description: |
        More specific data may be obtained through the following query filters.
        In its simplest form:

        * `column_name`=value:
            if column_name belongs to the column set
            then the result set will be filtered accordingly to the supplied value.

        For a wider range of values:

        * `ilikecolumn_name`=value:
            if column_name belongs to the column set
              and column type is text
            then filter column_name ilike '%value%'.

        * `filter_d_up_column_name`=value:
            if column_name belongs to the column set
              and column type is date
            then filter column_name >= value.

        * `filter_d_lo_column_name`=value:
            if column_name belongs to the column set
              and column type is date
            then filter column_name <= value.

        * `filter_d_eq_column_name`=value:
            if column_name belongs to the column set
              and column type is date
            then filter column_name == value.

        * `filter_n_up_column_name`=value: S
          if column_name belongs to the column set
            and column type is numeric
          then filter column_name >= value.

        * `filter_n_lo_column_name`=value:
            if column_name belongs to the column set
              and column type is numeric
            then filter column_name <= value.

        DDE: elementary exchange data
        DS: data source
        DSR: regional data sources
      tags:
        - Exports
      parameters:
        - name: id
          in: path
          description: The export ID
          required: true
          # type: integer
        - name: format
          in: path
          description: >
            Data format:
              * `json` - w/o geographic information
              * `csv` - w/o geographic information
              * `shp` - with geographic information
          type: string
          enum:
            - json
            - csv
            - shp
          required: true
        - name: permId
          in: query
          type: string
          # format: uuid
          description: >
            Unique and sustainable identifier of the observation DDE in the SINP, attributed by regional or thematic platform.
        - name: statObs
          in: query
          type: string
          enum: [No, Pr]
          description: >
            Indicates whether the taxon has been observed directly or indirectly (signs of presence, other clues), or not.
        - name: nomCite
          in: query
          type: string
          description: >
            The entire scientific name of the observed entity, including discovering authority if available, in the original dataset.
        - name: dateDebut
          in: query
          type: string
          # format: date-time
          description: >
            Observation date in the Gregorian calendar system.
            In case of inaccuracy, this attribute will be a rough estimate of the timeline.
        - name: dateFin
          in: query
          type: string
          # format: date-time
          description: End date of observation
        - name: heureDebut
          in: query
          type: string
          # format: full-time
          description: Hour and minute in the local system to which taxon observation started in ISO8601 format.
        - name: heureFin
          in: query
          type: string
          # format: full-time
          description: Hour and minute shown in local time where the taxon observation ended in ISO8601 format.
        - name: altMax
          in: query
          type: integer
          description: Maximum altitude of observation in meter.
        - name: altMin
          in: query
          type: integer
          description: Minimum altitude of observation in meter.
        - name: cdNom
          in: query
          type: integer
          description: Taxon code &#x201E;cd_nom&#x201E; of TaxRef, referencing the taxon at the national level.
        - name: cdRef
          in: query
          type: integer
          description: Taxon code &#x201E;cd_refs&#x201E; of TaxRef, referencing the taxon at the national level.
        - name: versionTAXREF
          in: query
          type: string
          description: current TAXREF version for this platform (SINP export).
        - name: datedet (SINP) | dateDet (DLB)
          in: query
          type: string
          # format: date-time
          description:  >
            Date of latest observation of the taxon in the Gregorian calendar.
        - name: comment
          in: query
          type: string
          description: Additional field to provide further information.
        - name: dSPublique
          in: query
          type: string
          enum: [Ac, Pr, Pu, Re, NSP]
          description: >
            Explicitly indicates whether the DS of the DEE is public or private.
            This field only defines the necessary and sufficient rights of the DS to produce a DEE:
            the public DSP must only be used to indicate if the resulting DEE is likely to be blurred
            and should not be used for a usage other than simple observation.
        - name: jddMetadonneeDEEId (SINP)
          in: query
          type: string
          # format: uuid
          description: UUID of the metadata record entered in the INPN application.
        - name: statSource
          in: query
          type: string
          description: >
            Indicates whether the observation DS comes directly from the field (via a computerized document or database),
            a collection or from literature (INPN = statut_source: id=19).
          enum: [Te, Co, Li, NSP]
        - name: diffusionNiveauPrecision (SINP)
          in: query
          type: string
          description: >
            Permission level granted by the owner if the data is private (attribute diffusion LevelPrecision of the standard DSR/DEE).
        - name: idOrigine
          in: query
          type: string
          # format: uuid
          description: >
            Unique identifier of the observation DataSource in the database, itself characterized by jddId and/or jddCode, where it is stored, and its initial form.
            This identifier must not be used as a key, which may vary depending on the management choices of the storage tool.
        - name: jddCode (SINP)
          in: query
          type: string
          description: The name, acronym, code, or initials identifying the origins of the collection or dataset. &#x201E;Ex:&#x201E; &#x201E;INPN&#x201E;, &#x201E;Silène&#x201E;, &#x201E;BDMAP&#x201E;.
        - name: jddId
          in: query
          type: string
          # format: uuid
          description: An identifier for the collection or terrain dataset from which the recording originates.
        - name: refBiblio
          in: query
          type: string
          description: ISO690 format preference for the observation source reference. The bibliographic reference must concern the observation itself and not only the taxon or the protocol.
        - name: obsMeth
          in: query
          type: string
          description: >
            Indicates how the presence of the subject was observed.
            (INPN = methode_obs)
        - name: ocEtatBio
          in: query
          type: string
          description: >
            Code of biological status of the organism at the time of observation.
            INPN = etat_bio
        - name: ocNat
          in: query
          type: string
          description: >
            Normalcy of the occurrence, consequence of the direct human influence which impacts it.
            It can be determined immediately by simple observation, including by a person who has no training in the field of biology.
            (INPN = naturalite)
        - name: ocSex
          in: query
          type: string
          description: Sex of the observation&#x27;s subject
        - name: ocStade
          in: query
          type: string
          description: Development&#x27;s stage of the observation&#x27;s subject.
        - name: ocBiogeo
          in: query
          type: integer
          description: >
            The biogeographical status covers a notion of presence (presence/absence), and origin (native or introduction).
            It is similar to the biogeographic status as per the TAXREF methodological reference, but applied at local level:
              it is information that can only be made by an expert.
        - name: ocStatBio
          in: query
          type: integer
          description: >
            General behavior of the individual at the observation site.
            (INPN = statut_bio)
        - name: preuveOui
          in: query
          type: string
          description: >
            Whether evidence exists or not, meaning a physical or digital object that can be used to demonstrate the existence of the occurrence.
        - name: ocMethDet
          in: query
          type: string
          description: determination method (GEONATURE = meth_determin)
        - name: preuvNum
          in: query
          type: string
          description: >
            Web address where we can find the digital evidence, or the archive containing all the digital evidence.
            (image(s), sonogram(s), film(s), genetic sequence(s) ...).
            (INPN = preuve_exist)
        - name: preuvNoNum
          in: query
          type: string
          description: >
            Address or name of the person or organization that would provide non-digital evidence of the observation.
        - name: obsCtx
          in: query
          type: string
          description: >
            Description of the observation&#x27;s context, as short and specific as possible.
        - name: permIdGrp
          in: query
          type: string
          # format: uuid
          description: >
            Permanent identifier of the grouping assigned by the regional or thematic platform.
        - name: methGrp
          in: query
          type: string
          description: >
            Description of the method leading to the grouping, as short as possible: free field.
        - name: typGrp
          in: query
          type: string
          enum: [Autr, Camp, InvSta, Lien, Obs, Op, Strat, Pass, NSP, ...]
          description: >
            Indicates what is the type of grouping according to the list `typeRegroupementValue`
            (INPN = Type de regroupement)
        - name: denbrMax
          in: query
          type: integer
          description: Maximum number of same taxon in an observation.
        - name: denbrMin
          in: query
          type: integer
          description: Minimum number of same taxon in an observation.
        - name: objDenbr
          in: query
          type: string
          description: >
            Indicates the object of the enumeration: individual, couple .... The terminology to be defined by thematic extension.
        - name: typDenbr
          in: query
          type: string
          enum: [Co, Es, Ca, NSP]
          description: Method used for counting (Inspire).
        - name: obsId
          in: query
          type: string
          description: Name and surname of the person(s) who made the observation.
        - name: obsNomOrg
          in: query
          type: string
          description: Name of the organization(s) the observer(s) belongs to.
        - name: detId
          in: query
          type: string
          description: First name, name and organization of the person(s) who made the taxonomic determination in the observation.
        - name: detNomOrg
          in: query
          type: string
          description: >
            Organism of the person(s) who made the determination of the taxon in the observation.
        - name: orgGestDat
          in: query
          type: string
          description: Name of the organization that is responsible for the DS of the DEE.
        - name: geom_4326
          in: query
          type: string
          description: >
            Geometry of the taxon occurrence observation. It can not be complex (point and line or polygon and line for example).
            It does not represent a connecting territory (the centroid of the municipality, the surface of a mesh) but the actual location of the observation.
        - name: WKT
          in: query
          type: string
          description: cf. geom_4326
        - name: natObjGeo
          in: query
          type: string
          enum: [St, In, NSP]
          description: Nature of the location transmitted.
      produces:
        - application/json
        - text/csv
        - application/zip
      responses:
        '200':
          description: Export data into a file
          schema:
            type: file
          headers:
            Content-Disposition:
              type: string
              description: attachment; filename=export_{Export.label}_{datetime.now().strftime('%Y_%m_%d_%Hh%Mm%S')}.{extension}
        '404':
          description: No configured export | Empty dataset | Unsuitable format
        '400':
          description: Unexpected usage
        '403':
          description: Unauthenticated | Insufficient rights
