swagger: "2.0"
info:
  version: "0.1.0"
  title: "Exports de JDD concernant la biodiversité"
  description: "Export de vos jeux de données GéoNature aux formats geojson, csv et shapefile"
  contact:
    name: API Support
    url: https://github.com/PnX-SI/GeoNature/issues
    email: geonature@ecrins-parcnational.fr
  license:
    name: GNU General Public License v3.0
    url: https://raw.githubusercontent.com/PnX-SI/GeoNature/master/LICENSE
externalDocs:
  description: "Find out more about GéoNature"
  url: "http://geonature.fr"
host: {{HOST}}
basePath: {{BASE_PATH}}
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
definitions:
  Export:
    type: object
    properties:
      id:
        type: integer
        minimum: 1
      label:
        type: string
      schema_name:
        type: string
      view_name:
        type: string
    required:
      - id
  Login:
    type: object
    properties:
      login:
        type: string
        default: "admin"
      password:
        type: string
        format: password
        default: "admin"
      id_application:
        type: integer
        default: 3
      with_cruved:
        type: boolean
        default: true
  Cruved:
    type: object
    properties:
      user:
        type: object
        properties:
          id_application:
            type: integer  # 3
          id_tag_action:
            type: integer  # 11
            maxLength: 2
          nom_role:
            type: string  # "Administrateur"
          identifiant:
            type: string  # "admin"
          rights:
            type: object
            properties:
              "3":
                type: object
                properties:
                  "R":
                    type: string  # "3"
                    maxLength: 1
                  "D":
                    type: string  # "3"
                    maxLength: 1
                  "E":
                    type: string  # "3"
                    maxLength: 1
                  "C":
                    type: string  # "3"
                    maxLength: 1
                  "V":
                    type: string  # "3"
                    maxLength: 1
                  "U":
                    type: string  # "3"
                    maxLength: 1
          id_organisme:
            type: integer  # -1
          tag_action_code:
            type: string  # "C"
          prenom_role:
            type: string  # "test"
          id_role:
            type: integer  # 1
          id_tag_object:
            type: integer  # 23
          tag_object_code:
            type: string  # "3"
      expires:
        type: string  # "2018-10-16 00:36:15.491613"
        format: datetime
  Error:
    type: object
    properties:
     message:
      type: string
     error:
      type: string
securityDefinitions:
  # tokenAuth:
  #   type: apiKey
  #   in: cookie
  #   name: token
  bearerAuth:
    type: apiKey
    in: header
    name: Authorization
paths:
  /auth/login:
    post:
      tags:
        - Authentification
      security:
        - bearerAuth: []
      summary:  Allow users to log in and to receive a token
      parameters:
        -
         in: body
         name: body
         description: username/password combination
         required: true
         schema:
           $ref: '#/definitions/Login'
      responses:
        '200':
           description: Login Success
           schema:
             $ref: '#/definitions/Cruved'
        '500':
           description:
             If supplied with invalid credentials
           schema:
             $ref: '#/definitions/Error'
  /{{API_URL}}/:
    get:
      security:
        # - tokenAuth: []
        - bearerAuth: []
      summary: Returns all exports the user has access to
      tags:
        - Exports
      responses:
        '200':
          description: A list of export
          schema:
            type: array
            items:
              $ref: '#/definitions/Export'
        '404':
          description: No configured exports
        '400':
          description: Unexpected usage
        '403':
          description: Unauthenticated
  /{{API_URL}}/{id}/{format}:
    get:
      security:
        # - tokenAuth: []
        - bearerAuth: []
      summary: Returns the format-specified data from the export the user has access to
      tags:
        - Exports
      parameters:
        - name: id
          in: path
          description: The export ID
          required: true
          type: integer
        - name: format
          in: path
          description: >
            Data format:
              * `json` - w/o geographic information
              * `csv` - w/o geographic information
              * `shp` - with geographic information
          type: string
          enum:
            - json
            - csv
            - shp
          required: true
        - name: permId
          in: query
          type: string
          format: uuid
          description:
        - name: statObs
          in: query
          type: string
          enum: [No, Pr]
          description: Indicates whether the taxon has been observed directly or indirectly (presence indices), or not observed
        - name: nomCite
          in: query
          type: string
          description: The entire scientific name of the observed entity, including authority if available, in the original dataset
        - name: dateDebut
          in: query
          type: string
          format: date-time
          description: Date of the day of the taxon observation in the Gregorian calendar system. In case inaccuracy in the date of the observation, this attribute represents the most old of the period of vagueness
        - name: dateFin
          in: query
          type: string
          format: date-time
          description: end of manifestation datetime of occurrence
        - name: heureDebut
          in: query
          type: string
          format: full-time
          description: start of manifestation time of occurrence
        - name: heureFin
          in: query
          type: string
          format: full-time
          description: end of manifestation time of occurrence
        - name: altMax
          in: query
          type: integer
          description:
        - name: altMin
          in: query
          type: integer
          description:
        - name: cdNom
          in: query
          type: integer
          description: Taxon code "cd_nom" of TaxRef, referencing the taxon at the national level
        - name: cdRef
          in: query
          type: integer
          description: Taxon code "cd_refs" of TaxRef, referencing the taxon at the national level
        - name: versionTAXREF
          in: query
          type: string
          description: current TAXREF version for this platform (SINP export)
        - name: datedet (SINP) | dateDet (DLB)
          in: query
          type: string
          format: date-time
          description: Date of the last determination of the taxon of the observation in the system Gregorian calendar
        - name: comment
          in: query
          type: string
          description:
        - name: dSPublique
          in: query
          type: string
          enum: [Ac, Pr, Pu, Re, NSP]
          description:
        - name: jddMetadonneeDEEId (SINP)
          in: query
          type: string
          format: uuid
          description: UUID of the metadata record entered in the INPN application
        - name: statSource
          in: query
          type: string
          description: "(INPN = statut_source: id = 19)"
          enum: [Co, Li, NSP, Te]
        - name: diffusionNiveauPrecision (SINP export)
          in: query
          type: string
          description:
        - name: idOrigine
          in: query
          type: string
          format: uuid
          description: unique_id_sinp_occtax
        - name: jddCode (SINP export)
          in: query
          type: string
          description: The name, acronym, code, or initial identifying the collection or dataset whose registration of the Source Data comes from. "Ex:" "INPN", "Silène", "BDMAP"
        - name: jddId
          in: query
          type: string
          format: uuid
          description: An identifier for the collection or terrain dataset from which the recording originates
        - name: refBiblio
          in: query
          type: string
          description: ISO690 format preference reference of the observation source. The bibliographic reference must concern the observation itself and not only the taxon or the protocol
        - name: obsMeth
          in: query
          type: string
          # minLength: 1
          # maxLength: 2
          default: "Inconnu"
          description: >
            observation method (INPN = methode_obs) => statSource = "Li"
        - name: ocEtatBio
          in: query
          type: string
          # minLength: 1
          # maxLength: 1
          default: "Inconnu"
          description: INPN = etat_bio
        - name: ocNat
          in: query
          type: string
          default: "Inconnu"
          description: INPN = naturalite
        - name: ocSex
          in: query
          type: string
          default: "Inconnu"
          description:
        - name: ocStade
          in: query
          type: string
          default: "Inconnu"
          description:
        - name: ocBiogeo
          in: query
          type: string
          default: "Inconnu"
          description:
        - name: ocStatBio
          in: query
          type: string
          default: "Inconnu"
          description: INPN = statut_bio
        - name: preuveOui
          in: query
          type: string
          description:
        - name: ocMethDet
          in: query
          type: string
          description: determination method (GEONATURE = meth_determin)
        - name: preuvNum
          in: query
          type: string
          description: digital proof (INPN = preuve_exist)
        - name: preuvNoNum
          in: query
          type: string
          default: "Inconnu"
          description: non digital proof
        - name: obsCtx
          in: query
          type: string
          description:
        - name: permIdGrp
          in: query
          type: string
          format: uuid
          description:
        - name: methGrp
          in: query
          type: string
          description:
        - name: typGrp
          in: query
          type: integer
          description: (INPN = Type de regroupement)
        - name: denbrMax
          in: query
          type: integer
          description:
        - name: denbrMin
          in: query
          type: integer
          description:
        - name: objDenbr
          in: query
          type: string
          description:
        - name: typDenbr
          in: query
          type: string
          description:
        - name: obsId
          in: query
          type: string
          description:
        - name: obsNomOrg
          in: query
          type: string
          description: Name of the organization(s) of the observer(s) within the framework from which the observation of the taxon has been made
        - name: detId
          in: query
          type: string
          description:
        - name: detNomOrg
          in: query
          type: string
          description:
        - name: orgGestDat
          in: query
          type: string
          description:
        - name: geom_4326
          in: query
          type: string
          description: geometry
        - name: WKT
          in: query
          type: string
          description:
        - name: natObjGeo
          in: query
          type: string
          description:
        - name: date_min
          in: query
          type: string
          format: date-time
        - name: date_max (DLB)
          in: query
          type: string
          format: date-time
          description:
        - name: id_dataset (DLB)
          in: query
          type: integer
          description:
        - name: id_releve_occtax (DLB)
          in: query
          type: integer
          format: int64
          description:
        - name: id_occurrence_occtax (DLB)
          in: query
          type: integer
          format: int64
          description:
        - name: id_digitiser (DLB)
          in: query
          type: integer
          description:
      produces:
        - application/json
        - text/csv
        - application/zip
      responses:
        '200':
          description: Export data into a file
          schema:
            type: file
          headers:
            Content-Disposition:
              type: string
              description: attachment; filename=export_{Export.label}_{datetime.now().strftime('%Y_%m_%d_%Hh%Mm%S')}.{extension}
          # examples:
          #   application/json: |
          #     [{
          #       "obsMeth": "23",                                           # some comment on this particular field
          #       "preuvNum": "",
          #       "permIdGrp": "51bd7642-512f-49aa-a917-cd2fcb8da1e3",
          #       "dateFin": "2017-01-01 00:00:00",
          #       "obsId": "Administrateur test",
          #       "statObs": "Pr",
          #       "statSource": null,
          #       "versionTAXREF": "Taxref V11.0",
          #       "ocMethDet": "Autre m\u00e9thode de d\u00e9termination",
          #       "ocEtatBio": "1",
          #       "denbrMin": 1,
          #       "denbrMax": 1,
          #       "dateDebut": "2017-01-01 00:00:00",
          #       "WKT": "POINT(6.5 44.85)",
          #       "cdRef": 351,
          #       "heureFin": "12:05:02",
          #       "ocStatBio": "1",
          #       "detNomOrg": "NSP",
          #       "ocStade": "4",
          #       "obsCtx": "Exemple test",
          #       "jddMetadonneeDEEId": "4d331cae-65e4-4948-b0b2-a11bc5bb46c2",
          #       "idOrigine": "5ce538fd-8143-4810-a6c8-7a98cf14f879",
          #       "preuvNoNum": "Poils de plumes",
          #       "detId": "Th\u00e9o",
          #       "jddId": "4d331cae-65e4-4948-b0b2-a11bc5bb46c2",
          #       "typDenbr": "Co",
          #       "preuveOui": "0",
          #       "permId": "5ce538fd-8143-4810-a6c8-7a98cf14f879",
          #       "datedet": "2017-01-01 00:00:00",
          #       "diffusionNiveauPrecision": "0",
          #       "altMax": 1565,
          #       "typGrp": "OBS",
          #       "comment": "Autre test",
          #       "ocBiogeo": "0",
          #       "obsNomOrg": "Autre",
          #       "cdNom": 351,
          #       "ocNat": "1",
          #       "jddCode": "Contact al\u00e9atoire tous r\u00e8gnes confondus",
          #       "orgGestDat": "NSP",
          #       "methGrp": "Relev\u00e9",
          #       "altMin": 1500,
          #       "ocSex": "2",
          #       "nomCite": "Grenouille rousse",
          #       "dSPublique": "NSP",
          #       "objDenbr": "IND",
          #       "heureDebut": "12:05:02",
          #       "refBiblio": null,
          #       "natObjGeo": "In"
          #     }, {
          #       "...": "..."
          #     }]
          #   text/csv: |
          #     permId,statObs,nomCite,dateDebut,dateFin,heureDebut,heureFin,altMax,altMin,cdNom,cdRef,versionTAXREF,datedet,comment,dSPublique,jddMetadonneeDEEId,statSource,diffusionNiveauPrecision,idOrigine,jddCode,jddId,refBiblio,obsMeth,ocEtatBio,ocNat,ocSex,ocStade,ocBiogeo,ocStatBio,preuveOui,ocMethDet,preuvNum,preuvNoNum,obsCtx,permIdGrp,methGrp,typGrp,denbrMax,denbrMin,objDenbr,typDenbr,obsId,obsNomOrg,detId,detNomOrg,orgGestDat,WKT,natObjGeo
          #     "5ce538fd-8143-4810-a6c8-7a98cf14f879","Pr","Grenouille rousse","2017-01-01 00:00:00","2017-01-01 00:00:00","12:05:02","12:05:02","1565","1500","351","351","Taxref V11.0","2017-01-01 00:00:00","Autre test","NSP","4d331cae-65e4-4948-b0b2-a11bc5bb46c2","","0","5ce538fd-8143-4810-a6c8-7a98cf14f879","Contact aléatoire tous règnes confondus","4d331cae-65e4-4948-b0b2-a11bc5bb46c2","","23","1","1","2","4","0","1","0","Autre méthode de détermination","","Poils de plumes","Exemple test","51bd7642-512f-49aa-a917-cd2fcb8da1e3","Relevé","OBS","1","1","IND","Co","Administrateur test","Autre","Théo","NSP","NSP","POINT(6.5 44.85)","In"
          #     "9f42bc38-2cae-4bb9-af2c-f76ef732b571","Pr","Lynx Boréal","2017-01-01 00:00:00","2017-01-01 00:00:00","12:05:02","12:05:02","1565","1500","60612","60612","Taxref V11.0","2017-01-01 00:00:00","Test","NSP","4d331cae-65e4-4948-b0b2-a11bc5bb46c2","","0","9f42bc38-2cae-4bb9-af2c-f76ef732b571","Contact aléatoire tous règnes confondus","4d331cae-65e4-4948-b0b2-a11bc5bb46c2","","23","1","1","2","2","0","1","0","Autre méthode de détermination","","Poil","Exemple test","51bd7642-512f-49aa-a917-cd2fcb8da1e3","Relevé","OBS","5","5","IND","Co","Administrateur test","Autre","Gil","NSP","NSP","POINT(6.5 44.85)","In"
          #     "eb67d3a2-c7f2-4340-820c-5c710b45bdf0","Pr","Ablette","2017-01-08 00:00:00","2017-01-08 00:00:00","20:00:00","23:00:00","1600","1600","67111","67111","Taxref V11.0","2017-01-08 00:00:00","Troisieme test","NSP","4d331cae-65e4-4948-b0b2-a11bc5bb46c2","","0","eb67d3a2-c7f2-4340-820c-5c710b45bdf0","Contact aléatoire tous règnes confondus","4d331cae-65e4-4948-b0b2-a11bc5bb46c2","","23","1","1","2","3","0","1","0","Autre méthode de détermination","","Poils de plumes","Autre exemple test","cb0b1e2e-9cb4-4714-baa8-9c293059a423","Relevé","OBS","1","1","IND","Co","Administrateur test","Autre","Donovan","NSP","NSP","POINT(6.5 44.85)","In"
        '404':
          description: No configured export | Empty dataset | Unsuitable format
        '400':
          description: Unexpected usage
        '403':
          description: Unauthenticated | Insufficient rights
